spring.application.name=PRODUCT-CATALOG-SERVICE
server.port=8082

# Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=product_catalog_service;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=phuocga147
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=your-secret-key-min-32-chars-long-for-security
jwt.expiration=86400000